In [2]:
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
import pandas as pd
import numpy as np

# 1. Загружаем датасет
housing = fetch_openml(name="house_prices", as_frame=True, parser="auto")
df = housing.frame

# Возьмем 3 разных категориальных признака:
# - CentralAir: Есть ли центральное кондиционирование ('Y', 'N') — Бинарный/Номинальный
# - KitchenQual: Качество кухни ('Ex', 'Gd', 'TA', 'Fa', 'Po') — Порядковый (Ordinal)
# - Neighborhood: Район города (25 уникальных районов) — Номинальный с высокой мощности (High Cardinality)

X = df[['CentralAir', 'KitchenQual', 'Neighborhood']].copy()
y = df['SalePrice'].copy()
X.head()

  CentralAir KitchenQual Neighborhood
0          Y          Gd      CollgCr
1          Y          TA      Veenker
2          Y          Gd      CollgCr
3          Y          Gd      Crawfor
4          Y          Gd      NoRidge

In [3]:
# 1
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.head()

     CentralAir KitchenQual Neighborhood
254           Y          TA        NAmes
1066          Y          TA      Gilbert
638           Y          TA      Edwards
799           Y          Gd        SWISU
380           Y          Gd        SWISU

In [4]:
# 2
encoder = OrdinalEncoder(categories=[['Po', 'Fa', 'TA', 'Gd', 'Ex']])
X_train['KitchenQual_encoded'] = encoder.fit_transform(X_train[['KitchenQual']])

X_test['KitchenQual_encoded'] = encoder.transform(X_test[['KitchenQual']])
X_train.head()

     CentralAir KitchenQual Neighborhood  KitchenQual_encoded
254           Y          TA        NAmes                  2.0
1066          Y          TA      Gilbert                  2.0
638           Y          TA      Edwards                  2.0
799           Y          Gd        SWISU                  3.0
380           Y          Gd        SWISU                  3.0

In [5]:
encoder = OneHotEncoder(drop='first', sparse_output=False)
X_train['CentralAir_encoded'] = encoder.fit_transform(X_train[['CentralAir']])

X_test['CentralAir_encoded'] = encoder.transform(X_test[['CentralAir']])
X_train.head()

,CentralAir,KitchenQual,Neighborhood,KitchenQual_encoded,CentralAir_encoded
254,Y,TA,NAmes,2.0,1.0
1066,Y,TA,Gilbert,2.0,1.0
638,Y,TA,Edwards,2.0,1.0
799,Y,Gd,SWISU,3.0,1.0
380,Y,Gd,SWISU,3.0,1.0

In [7]:
print(X_train['Neighborhood'].nunique())

25